import '../account'
import './profilepage.css'
import '../message.css'
import '../player-name-register'
import '../player-email-register'
import '../claim-player-by-token'
import '../reset-login-by-token'
import '../login-by-email'
