---

- name: Remove certbot and delete certificate
  hosts: all
  user: dev
  become: true
  tasks:

    - name: Delete provisioned cert for domain
      command: "certbot delete --cert-name {{ domain_name }} --non-interactive"

    - name: Remove certbot snap
      community.general.snap:
        name: certbot
        classic: yes
        state: absent

    - name: Remove the certbot command by removing symlink to /usr/bin/
      ansible.builtin.file:
        src: /snap/bin/certbot
        dest: /usr/bin/certbot
        state: absent
